//! All messages the UI can send: navigation, transport, library,
//! scheduler, carts, reports, ads, settings, and backup.
//! The central dispatcher in `update` matches on these and delegates
//! to one domain function each.

use std::path::PathBuf;

use crabcore::library::TrackKind;
use crabcore::stream::{StreamFormat, StreamProtocol};

use super::{Screen, SettingsSection};

#[derive(Debug, Clone)]
pub(crate) enum Message {
    Navigate(Screen),
    SettingsNav(SettingsSection),
    Tick,
    // Transport
    Play,
    Pause,
    Stop,
    Next,
    Prev,
    /// Deliberate cut: fire the selected library track on program now
    /// (crossfade when live). The per-row buttons are cue-only, so this
    /// — sitting in the program strip — is the one explicit on-air gate.
    PlaySelected,
    VolumeChanged(f32),
    AutodjToggled(bool),
    // Library
    LibrarySearchChanged(String),
    LibraryKindChanged(Option<TrackKind>),
    LibraryMissingToggled(bool),
    LibraryDupesToggled(bool),
    LibraryTrackSelected(usize),
    LibraryCuePlay(usize),
    LibraryCueStop(),
    ImportFiles,
    ImportFilesPicked(Vec<PathBuf>),
    HealthCheck,
    LoudnessScan,
    AutoSyncToggled(bool),
    AutoSyncIntervalInc,
    AutoSyncIntervalDec,
    WatchFolderAdd,
    WatchFolderRemove(usize),
    // Rotation generator (Home panel)
    GenHourInc(usize),
    GenHourDec(usize),
    GenCountInc(usize),
    GenCountDec(usize),
    GenFire(usize),
    GenFireAll,
    PlaylistToAir(String),
    // Manual builder (B): create/select/detail/reorder on Home.
    PlaylistNewName(String),
    PlaylistCreate,
    PlaylistSelect(String),
    PlaylistDelete(String),
    PlaylistAddSelected(String),
    PlaylistRemoveItem(String, usize),
    PlaylistMoveUp(String, usize),
    PlaylistMoveDown(String, usize),
    // P0: rename (core existed, UI missing) + m3u interchange.
    PlaylistRenameInput(String),
    PlaylistRename(String),
    PlaylistExport(String),
    PlaylistImport,
    // Scheduler
    SchedulerMasterToggled(bool),
    SchedulerToggleEvent(usize),
    SchedulerDeleteEvent(usize),
    SchedulerRunEvent(usize),
    SchedulerNew,
    SchedulerEdit(usize),
    SchedulerEditorClose,
    SchedName(String),
    SchedTime(String),
    SchedTarget(String),
    SchedExpires(String),
    SchedActionPrev,
    SchedActionNext,
    SchedDayChanged(usize, bool),
    SchedulerSave,
    // Carts
    CartPlay(usize),
    CartHotkey(usize),
    CartDelete(usize),
    CartAdd,
    CartPlace(usize),
    CartToggleAssign,
    // Reports
    ReportRangeChanged(usize),
    ReportExport,
    // Ads
    AdsToggle(usize),
    AdsDelete(usize),
    AdsRun(usize),
    AdsNew,
    AdsEdit(usize),
    AdsEditorClose,
    AdName(String),
    AdSpot(String),
    AdIntro(String),
    AdOutro(String),
    AdStart(String),
    AdEnd(String),
    AdTime(String),
    AdDayChanged(usize, bool),
    AdsSave,
    // Settings
    SettingsRefreshDevices,
    SettingsSelectDevice(String),
    CueSelectDevice(String),
    CueVolumeInc,
    CueVolumeDec,
    XfadeInc,
    XfadeDec,
    SilenceInc,
    SilenceDec,
    EqToggle,
    EqSet(usize, f32),
    EqSave,
    EqReset,
    LimiterInc,
    LimiterDec,
    LoudnessToggle,
    LoudnessTargetInc,
    LoudnessTargetDec,
    StreamToggle,
    StreamTlsToggle,
    StreamHost(String),
    StreamUsername(String),
    StreamPort(String),
    StreamMount(String),
    StreamPassword(String),
    StreamPasswordClear,
    StreamBitrateInc,
    StreamBitrateDec,
    StreamFormatChanged(StreamFormat),
    StreamProtocolChanged(StreamProtocol),
    StreamSidInc,
    StreamSidDec,
    StreamRestart,
    // Optional on-air DSP (Thimeo Stereo Tool, stream path)
    StToggle,
    StBypassToggle,
    StLibPath(String),
    StLicenseKey(String),
    StPresetPath(String),
    MicToggle,
    MicRefreshDevices,
    MicSelectDevice(String),
    MicLevelInc,
    MicLevelDec,
    MicDuckToggle,
    MicThresholdInc,
    MicThresholdDec,
    MicDepthInc,
    MicDepthDec,
    MicAttackInc,
    MicAttackDec,
    MicReleaseInc,
    MicReleaseDec,
    StationName(String),
    BackupNow,
    RestoreNow,
}
