//! All messages the UI can send: navigation, transport, library,
//! scheduler, carts, reports, ads, settings, backup, and license.
//! The central dispatcher in `update` matches on these and delegates
//! to one domain function each.

use crabcore::library::TrackKind;
use crabcore::stream::StreamFormat;

use super::{Screen, SettingsSection};

#[derive(Debug, Clone)]
pub(crate) enum Message {
    Navigate(Screen),
    SettingsNav(SettingsSection),
    Tick,
    // Transport
    Play,
    Pause,
    Stop,
    Next,
    Prev,
    VolumeChanged(f32),
    AutodjToggled(bool),
    // Library
    LibrarySearchChanged(String),
    LibraryKindChanged(Option<TrackKind>),
    LibraryMissingToggled(bool),
    LibraryDupesToggled(bool),
    LibraryTrackSelected(usize),
    LibraryTrackPlay(usize),
    ImportFiles,
    HealthCheck,
    LoudnessScan,
    // Scheduler
    SchedulerMasterToggled(bool),
    SchedulerToggleEvent(usize),
    SchedulerDeleteEvent(usize),
    SchedulerRunEvent(usize),
    SchedulerNew,
    SchedulerEdit(usize),
    SchedulerEditorClose,
    SchedName(String),
    SchedTime(String),
    SchedTarget(String),
    SchedExpires(String),
    SchedActionPrev,
    SchedActionNext,
    SchedDayChanged(usize, bool),
    SchedulerSave,
    // Carts
    CartPlay(usize),
    CartHotkey(usize),
    CartDelete(usize),
    CartAdd,
    CartPlace(usize),
    CartToggleAssign,
    // Reports
    ReportRangeChanged(usize),
    ReportExport,
    // Ads
    AdsToggle(usize),
    AdsDelete(usize),
    AdsRun(usize),
    AdsNew,
    AdsEdit(usize),
    AdsEditorClose,
    AdName(String),
    AdSpot(String),
    AdIntro(String),
    AdOutro(String),
    AdStart(String),
    AdEnd(String),
    AdTime(String),
    AdDayChanged(usize, bool),
    AdsSave,
    // Settings
    SettingsRefreshDevices,
    SettingsSelectDevice(String),
    XfadeInc,
    XfadeDec,
    SilenceInc,
    SilenceDec,
    EqToggle,
    EqInc(usize),
    EqDec(usize),
    EqReset,
    LimiterInc,
    LimiterDec,
    LoudnessToggle,
    LoudnessTargetInc,
    LoudnessTargetDec,
    StreamToggle,
    StreamTlsToggle,
    StreamHost(String),
    StreamUsername(String),
    StreamPort(String),
    StreamMount(String),
    StreamPassword(String),
    StreamPasswordClear,
    StreamBitrateInc,
    StreamBitrateDec,
    StreamFormatChanged(StreamFormat),
    MicToggle,
    MicRefreshDevices,
    MicSelectDevice(String),
    MicLevelInc,
    MicLevelDec,
    MicDuckToggle,
    MicThresholdInc,
    MicThresholdDec,
    MicDepthInc,
    MicDepthDec,
    MicAttackInc,
    MicAttackDec,
    MicReleaseInc,
    MicReleaseDec,
    StationName(String),
    BackupNow,
    RestoreNow,
    // License
    LicenseKeyInput(String),
    ActivateLicense,
    ClearLicense,
}
